src/Illuminati/OrderBundle/Entity/Host_order.php
<?php

namespace Illuminati\OrderBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Host_order
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Illuminati\OrderBundle\Entity\Host_orderRepository")
 */
class Host_order
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Illuminati\UserBundle\Entity\User", inversedBy="hosted_orders")
     * @ORM\JoinColumn(name="users_id", referencedColumnName="id")
     */
    private $usersId;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank(message="notBlank.title")
     * @Assert\Length(
     *      min="3",
     *      max="255",
     *      minMessage="min.Title",
     *      maxMessage="max.Title"
     * )
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank(message="notBlank.description")
     * @Assert\Length(
     *      min="5",
     *      minMessage="min.Description"
     * )
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="close_date", type="datetime")
     * @Assert\GreaterThan("+1 minutes",message="pastDate")
     */
    private $closeDate;

        /**
         * @var integer
         * @ORM\Column(name="state_id", type="smallint")
         */
        private $stateId;

    /**
     * @var integer
     *
     * @ORM\Column(name="deleted", type="smallint")
     */
    private $deleted;

    //    /**
    //     * @ORM\OneToMany(targetEntity="Illuminati\OrderBundle\Entity\Order_participants", mappedBy="hostOrderId")
    //     */
    //    private $order_participants;

    /**
     * @var string
     *
     * @ORM\Column(name="order_token", type="string", length=32, unique=true)
     */
    private $orderToken;

    /**
     * @ORM\OneToMany(targetEntity="Illuminati\OrderBundle\Entity\User_order", mappedBy="hostOrderId")
     */
    private $user_orders;

    /**
     * @ORM\ManyToOne(targetEntity="Illuminati\ProductBundle\Entity\Supplier", inversedBy="host_order_id")
     * @ORM\JoinColumn(name="supplier_id", referencedColumnName="id")
     */
    private $supplier_id;

    /**
     * @ORM\OneToMany(targetEntity="Illuminati\OrderBundle\Entity\User_order_details", mappedBy="hostOrderId")
     */
    private $orderDetails;

    public function __construct()
    {
        $this->stateId = 1;
        $this->orderToken = bin2hex(openssl_random_pseudo_bytes(32));
        $this->deleted = 0;
        //$this->order_participants = new ArrayCollection();
        $this->user_orders = new ArrayCollection();
        $this->orderDetails = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set usersId
     *
     * @param integer $usersId
     *
     * @return Host_order
     */
    public function setUsersId($usersId)
    {
        $this->usersId = $usersId;

        return $this;
    }

    /**
     * Get usersId
     *
     * @return integer
     */
    public function getUsersId()
    {
        return $this->usersId;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Host_order
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Host_order
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set closeDate
     *
     * @param \DateTime $closeDate
     *
     * @return Host_order
     */
    public function setCloseDate($closeDate)
    {
        $this->closeDate = $closeDate;

        return $this;
    }

    /**
     * Get closeDate
     *
     * @return \DateTime
     */
    public function getCloseDate()
    {
        return $this->closeDate;
    }

    /**
     * Set stateId
     *
     * @param integer $stateId
     *
     * @return Host_order
     */
    public function setStateId($stateId)
    {
        $this->stateId = $stateId;

        return $this;
    }

    /**
     * Get stateId
     *
     * @return integer
     */
    public function getStateId()
    {
        return $this->stateId;
    }

    /**
     * Set deleted
     *
     * @param integer $deleted
     *
     * @return Host_order
     */
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return integer
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    //    /**
    //     * Get Order Participants
    //     *
    //     * @return mixed
    //     */
    //    public function getOrderParticipants()
    //    {
    //        return $this->order_participants;
    //    }

    /**
     * @return mixed
     */
    public function getUserOrders()
    {
        return $this->user_orders;
    }

    /**
     * @return mixed
     */
    public function getSupplierId()
    {
        return $this->supplier_id;
    }

    /**
     * @param mixed $supplier_id
     */
    public function setSupplierId($supplier_id)
    {
        $this->supplier_id = $supplier_id;
    }

    /**
     * @return string
     */
    public function getOrderToken()
    {
        return $this->orderToken;
    }

    /**
     * @return mixed
     */
    public function getOrderDetails()
    {
        return $this->orderDetails;
    }



}

src/Illuminati/OrderBundle/Controller/DefaultController.php
<?php

namespace Illuminati\OrderBundle\Controller;

use Illuminati\OrderBundle\Entity\User_order;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Illuminati\OrderBundle\Form\Host_orderType;
use Illuminati\OrderBundle\Entity\Host_order;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    /**
     * Redirect to new host order creation form
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function indexAction()
    {
        return $this->redirectToRoute("host_order_new");
    }

    /**
     * Host Order creation form
     * @param Request $request Submitted form request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request)
    {
        $hostOrder = new Host_order();

        //Prefilling the form with some data
        //Assigning hostOrder to the user

        $userObject = $this->get("security.token_storage")->getToken()->getUser();

        $hostOrder->setUsersId($userObject);
        $hostOrder->setCloseDate(new \DateTime("now"));

        $form = $this->createForm(new Host_orderType, $hostOrder);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($hostOrder);

            // Creating User_order for the host user

            $userOrder = new User_order();
            $userOrder->setHostOrderId($hostOrder);
            $userOrder->setUsersId($userObject);
            $em->persist($userOrder);
            $em->flush();

            $notificationMessage = $this->get('translator')
                ->trans('order.summary.successCreate');

            $this->get('session')->getFlashBag()
                ->add('success', $notificationMessage);

            return $this->redirectToRoute(
                'host_order_summary',
                ['id' => $hostOrder->getId()]
            );
        }

        return $this->render(
            "IlluminatiOrderBundle:Default:orderCreation.html.twig",
            ["form" => $form->createView(), 'pageTitle' => 'order.create']
        );
    }

    /**
     * Host order summary
     * @param string $id Host order id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|
     *         \Symfony\Component\HttpFoundation\Response
     */
    public function summaryAction($id)
    {
        if (($hostOrderObj = $this->get('host_order_participation_checker')->check((int)$id))) {
            //getting participants

            $em = $this->getDoctrine()->getManager()
                ->getRepository("IlluminatiOrderBundle:Host_order");

            $participants = $em->findUserOrders($id);

            $markAsPaidForms = [];
            foreach ($participants as $participant) {
                if ($participant->getPayed() == 0) {
                    $form = $this->generateCSRFprotectionForm(
                        $this->generateUrl(
                            'mark_as_paid',
                            [
                                'hostOrderId'=>$hostOrderObj->getId(),
                                'userOrderId'=>$participant->getId()
                            ]
                        )
                    );

                    $markAsPaidForms[] = [
                        'orderId' => $participant->getId(),
                        'form' => $form->createView()
                    ];
                }
            }

            $participantsOrders = $em->findUsersOrderDetails($id);

            $leaveOrderForm = $this->generateCSRFprotectionForm(
                $this->generateUrl('host_order_leave', ['id'=>$hostOrderObj->getId()])
            )->createView();

            return $this->render(
                "IlluminatiOrderBundle:Default/Summary:base.html.twig",
                [
                    'hostOrder'          => $hostOrderObj,
                    'participants'       => $participants,
                    'participantsOrders' => $participantsOrders,
                    'forms'              => $markAsPaidForms,
                    'leaveOrderForm'     => $leaveOrderForm
                ]
            );
        } else {
            return $this->redirectToRoute('homepage');
        }
    }

    /**
     * Host order edit page
     *
     * @param Request $request Submitted form request
     * @param integer $id      Host order id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|
     *          \Symfony\Component\HttpFoundation\Response
     */
    public function editHostOrderAction(Request $request, $id)
    {
        if (($hostOrder = $this->get('host_order_host_checker')->check((int)$id))) {
            if ($hostOrder->getStateId() != 1) {
                $notificationMessage = $this
                    ->get('translator')
                    ->trans("notify.messages.warning.cantEditClosedOrder");
                $this->get('session')->getFlashBag()->add('info', $notificationMessage);

                return $this->redirectToRoute('host_order_summary', ['id'=>$hostOrder->getId()]);
            }

            $em = $this
                ->getDoctrine()
                ->getManager();

            $form = $this->createForm(new Host_orderType, $hostOrder);

            // changing submit button label
            $form->remove('submit');
            $form->add('submit', 'submit', array("label" => "order.update"));

            $form->handleRequest($request);

            if ($form->isValid()) {
                $em->flush();

                $notificationMessage = $this->get('translator')
                    ->trans('order.summary.successUpdate');

                $this->get('session')->getFlashBag()
                    ->add('success', $notificationMessage);

                return $this->redirectToRoute(
                    'host_order_summary',
                    ['id' => $hostOrder->getId()]
                );
            }

            return $this->render(
                "IlluminatiOrderBundle:Default:orderCreation.html.twig",
                ["form" => $form->createView(), 'pageTitle' => 'order.edit']
            );
        } else {
            return $this->redirectToRoute('homepage');
        }

    }

    /**
     * Sends reminder emails to order participants who owe money
     *
     * @param integer $id Host order id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function debtReminderAction($id)
    {
        if (($hostOrder = $this->get('host_order_host_checker')->check((int)$id))) {
            $em = $this->getDoctrine()->getManager();
            $debtors = $em
                ->getRepository('IlluminatiOrderBundle:Host_order')
                ->findOrderDebtors($id);

            $emailSentCount = 0;

            $hostUserId = $hostOrder->getUsersId()->getId();

            foreach ($debtors as $debtor) {
                // don't send debt reminder email to the host.
                if ($debtor->getId() === $hostUserId) {
                    continue;
                }

                $message = \Swift_Message::newInstance()
                    ->setSubject('Group order product payment reminder')
                    ->setFrom('info@illuminati.org')
                    ->setTo($debtor->getEmail())
                    ->setBody(
                        $this->renderView(
                            'IlluminatiOrderBundle:Emails:debtEmail.html.twig',
                            [
                                'hostOrder' => $hostOrder,
                                'debtor'    => $debtor
                            ]
                        ),
                        'text/html'
                    );

                $this->get('mailer')->send($message);

                $emailSentCount++;
            }

            if ($emailSentCount > 1) {
                $notificationMessage = $this->get('translator')->trans(
                    'order.summary.successEmailSent_%count%',
                    ['%count%' => $emailSentCount]
                );

                $this->get('session')->getFlashBag()
                    ->add('success', $notificationMessage);
            } elseif ($emailSentCount == 0 && sizeof($debtors) == 1) {
                $notificationMessage = $this->get('translator')->trans(
                    'order.summary.noDebtors'
                );

                $this->get('session')->getFlashBag()
                    ->add('info', $notificationMessage);
            }

            return $this->redirectToRoute(
                "host_order_summary",
                ['id' => $hostOrder->getId()]
            );

        } else {
            return $this->redirectToRoute('homepage');
        }

    }

    /**
     * Shows Order History
     * @param $type
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showHistoryAction($type)
    {
        $userId = $this->container->get('security.token_storage')->getToken()->getUser()->getId();
        $em = $this->getDoctrine()->getManager();

        if ($type === 'hosted') {
            $orders = $em->getRepository('IlluminatiOrderBundle:Host_order')
                ->findHostedOrders($userId);

            return $this->render('IlluminatiOrderBundle:Default/History:history.html.twig', array(
                'orders'=>$orders,
                'type'=>$type,
            ));
        } elseif ($type === 'joined') {
            $orders = $em->getRepository('IlluminatiOrderBundle:Host_order')
                ->findJoinedOrders($userId);

            return $this->render('IlluminatiOrderBundle:Default/History:history.html.twig', array(
                'orders'=>$orders,
                'type'=>$type,
            ));
        } else {
            return $this->redirectToRoute('homepage');
        }
    }

    /**
     * Host order joining
     *

src/Illuminati/OrderBundle/Resources/views/Default/Summary/base.html.twig
{% extends ":default:index.html.twig" %}

{% block body %}
    <div class="container">
        <h1>{% trans %}order.summary.title{% endtrans %}</h1>

        <div class="jumbotron">
            <div class="row">
                <div class="col-sm-9">
                    <h2>{{ hostOrder.title }}</h2>
                    <p>{{ hostOrder.description }}</p>
                    <p><em><strong>{% trans %}order.supplier{% endtrans %}: {{ hostOrder.supplierId.name }}</strong></em></p>
                    <p><em><strong>{% trans %}order.summary.dueDate{% endtrans %} : {{ hostOrder.closeDate|date('Y-m-d H:i') }}</strong></em></p>
                </div>
                <div class="col-sm-3 text-center">
                    <h3>{{ "order.summary.hostedBy"|trans }}</h3>
                    <img class="img img-circle" src="{{ gravatar(hostOrder.usersId.email,100) }}" alt="host avatar">
                    <p>{{ hostOrder.usersId.name }} {{ hostOrder.usersId.surname }}</p>
                </div>
            </div>

           <div class="row">
               <div class="has-success">
                   <label for="inv_link">{% trans %}order.summary.inviteLink{% endtrans %} :</label>
                   <input class="form-control" id="inv_link" type="text" value="{{ app.request.getSchemeAndHttpHost() ~ path('host_order_join',{'hostOrderToken':hostOrder.orderToken}) }}" readonly>
               </div>
           </div>
        </div>

        {# Checking if host order's state is open #}
        {% if hostOrder.stateId == 1 %}
            {% if hostOrder.closeDate|date('Y-m-d H:i') > "now"|date("Y-m-d H:i") %}
                <a href="{{ path('product', { orderId : hostOrder.id } ) }}"><button class="btn btn-default"><span class="glyphicon glyphicon-shopping-cart"></span> {% trans %}order.summary.goToShopButton{% endtrans %} </button></a>
            {% endif %}
            {% if app.user.id == hostOrder.usersId.id %}
                <a href="{{ path('host_order_edit',{'id':hostOrder.id}) }}"><button class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> {% trans %}order.summary.editOrderButton{% endtrans %} </button></a>
            {% endif %}
        {% endif %}

        <hr>

        {# summary widget #}
        {% if (participants is defined) and (participants is not empty) %}
            {% set vars = { 'participants': participants , 'participantsOrders' : participantsOrders, 'hostOrder' : hostOrder, 'forms': forms  } %}
            {% include "IlluminatiOrderBundle:Default/Summary:summaryWidget.html.twig" with vars %}
        {% endif %}


        {# Checking if the logged in user is the host of the main order #}
        {% if hostOrder.usersId.id == app.user.id %}
            <hr>
            <div class="btn-group" role="group">
                <a id="send-reminder-emails" class="btn btn-default" href="{{ path('host_order_email_reminders',{'id':hostOrder.id}) }}"><span class="glyphicon glyphicon-envelope"></span> {% trans %}order.summary.remindAboutPaymentsButton{% endtrans %}</a>

                {# Checking if the logged in user is the host of the main order #}
                {% if hostOrder.stateId == 1 %}
                    <a class="btn btn-success" href="{{ path('host_order_confirm',{'id':hostOrder.id}) }}"><span class="glyphicon glyphicon-ok"></span> {% trans %}order.summary.confirmOrderButton{% endtrans %}</a>
                {% else %}
                    <a href="{{ path('host_order_generate_pdf', {'id': hostOrder.id}) }}" target="_blank" class="btn btn-default"><span class="glyphicon glyphicon-save-file"></span>  {{ "order.summary.confirmation.genPDF"|trans }}</a>
                {% endif %}

            </div>
        {% endif %}

        {# Checking if the logged in user is the host of the main order #}
        {% if hostOrder.stateId == 1 %}
        <div class="pull-right">
            {% if hostOrder.usersId.id == app.user.id %}
                <p class="alert-danger help-block"><strong>{% trans %}notify.error{% endtrans %}</strong> {% trans %}notify.messages.warning.hostLeavesGroupOrder{% endtrans %}</p>
            {% endif %}
            {{ form_start(leaveOrderForm) }}
            <button class="btn btn-danger pull-right" type="submit"><span class="glyphicon glyphicon-log-out"></span> {% trans %}order.summary.leaveOrder{% endtrans %}</button>
            {{ form_end(leaveOrderForm) }}
        </div>
        {% endif %}
        <br>

    </div>
{% endblock %}

src/Illuminati/OrderBundle/Resources/views/Default/Summary/summaryWidget.html.twig
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    {% for i in 0..participants|length-1 %}
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading{{ i }}">
                <div class="panel-title">
                    <img class="img img-circle" src="{{ gravatar(participants[i].usersId.email,25) }}" alt="user avatar">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ i }}" aria-expanded="false" aria-controls="collapse{{ i }}">
                        {{ participants[i].usersId.name }}
                        {{ participants[i].usersId.surname }}
                    </a>
                    <div class="pull-right">
                        {# showing payment statuses ONLY for order participants #}
                        {% if participants[i].usersId != hostOrder.usersId %}

                            {% if participants[i].payed == 0 %}
                                {# Only show forms for host of the order #}
                               {% if hostOrder.usersId.id == app.user.id %}
                                   {# Looking for the correct form #}
                                   {% for form in forms %}
                                        {% if form.orderId == participants[i].id %}
                                            {{ form_start(form.form) }}
                                                <button class="btn btn-xs btn-danger submit-mark-as-paid" type="submit" data-toggle="tooltip" data-placement="top" title="{% trans %}order.summary.widget.markAsPaid{% endtrans %}">{% trans %}order.summary.widget.notPaid{% endtrans %}</button>
                                            {{ form_end(form.form) }}
                                            <span class="label label-success marked-as-paid hidden">
                                                {% trans %}order.summary.widget.paid{% endtrans %}
                                            </span>
                                        {% endif %}
                                   {% endfor %}
                               {% else %}
                                   <span class="label label-danger">
                                       {% trans %}order.summary.widget.notPaid{% endtrans %}
                                   </span>
                               {% endif %}

                            {% else %}

                                <span class="label label-success">{% trans %}order.summary.widget.paid{% endtrans %}</span>

                            {% endif %}

                        {% else %}
                            <span class="label label-warning">Host</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="collapse{{ i }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ i }}">
                <div class="panel-body">
                    <table class="table table-responsive">
                        <tr>
                            <th>{% trans %}order.summary.widget.product{% endtrans %}</th>
                            <th class="col-sm-2">{% trans %}order.summary.widget.quantity{% endtrans %}</th>
                            <th class="col-sm-2">{% trans %}order.summary.widget.price{% endtrans %}</th>
                        </tr>
                        {% set sum = 0 %}
                        {% if participantsOrders is not empty %}
                           {% for y in 0..participantsOrders|length-1 %}
                               {% if participantsOrders[y].userId.id == participants[i].usersId.id %}
                                   <tr>
                                       <td>
                                           <img class="img img-thumbnail" src="{{ participantsOrders[y].productId.image }}" width="50px" alt="product image">
                                           <a href="{{ path('product_show',{'id':participantsOrders[y].productId.id, 'orderId': participantsOrders[y].hostOrderId.id}) }}"> {{ participantsOrders[y].productId.title }}</a>
                                       </td>
                                       <td>{{ participantsOrders[y].quantity }}</td>
                                       <td>{{ participantsOrders[y].productId.price ~ " " ~ participantsOrders[y].productId.currency }}</td>
                                   </tr>
                                   {% set sum = sum + participantsOrders[y].productId.price * participantsOrders[y].quantity %}
                               {% endif %}
                           {% endfor %}
                        {% endif %}
                        {% if sum > 0 %}
                            <tfoot>
                            <tr>
                                <th></th>
                                <th>Sum</th>
                                <th>{{ sum ~ " " ~ participantsOrders[0].productId.currency}}</th>
                            </tr>
                            </tfoot>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
    {% endfor %}
</div>